let dados = [
    {
        titulo: "Fusca",
        marca: "Volkswagen",
        descricao: 'O Volkswagen Fusca, mais do que um simples automóvel, é um ícone da indústria automobilística. Nascido na Alemanha nazista, o Fusca tornou-se um símbolo da reconstrução alemã após a Segunda Guerra Mundial. Sua produção em massa e design atemporal o tornaram um dos carros mais populares do século XX.',
        motor: "Motor 1600",
        preco: "R$ 25.000",
        cor: "Azul",
        ano: "1974",
        cambio: "Manual",
        potencia: "60 cv",
        tags: "clássico, icônico, Volkswagen, vintage",
        id:"1"
    },
    {
        titulo: "Nissan Kicks",
        marca: "Nissan",
        descricao: 'O Nissan Kicks é um SUV compacto projetado para o mercado urbano. Com seu design moderno e uma série de recursos tecnológicos, ele oferece conforto e praticidade em qualquer viagem.',
        motor: "1.6 Flex",
        preco: "R$ 120.000",
        cor: "Branco",
        ano: "2023",
        cambio: "CVT",
        potencia: "114 cv",
        tags: "SUV, urbano, moderno, tecnologia",
        id:"2"
    },
    {
        titulo: "Nissan Frontier",
        marca: "Nissan",
        descricao: 'A Nissan Frontier é uma picape robusta, conhecida por sua durabilidade e desempenho em terrenos difíceis. Com um motor potente e uma carroceria reforçada, é ideal para o trabalho pesado.',
        motor: "2.3 Turbo Diesel",
        preco: "R$ 250.000",
        cor: "Preto",
        ano: "2023",
        cambio: "Automático",
        potencia: "190 cv",
        tags: "picape, robusta, off-road, durabilidade",
        id:"3"
    },
    {
        titulo: "Nissan Versa",
        marca: "Nissan",
        descricao: 'O Nissan Versa combina economia de combustível, conforto e um design elegante. Ele é uma opção popular para quem busca um sedã acessível e confiável.',
        motor: "1.6 Flex",
        preco: "R$ 90.000",
        cor: "Prata",
        ano: "2023",
        cambio: "Manual",
        potencia: "114 cv",
        tags: "sedã, econômico, acessível, confiável",
        id:"4"
    },
    {
        titulo: "Nissan Protect",
        marca: "Nissan",
        descricao: 'O Nissan Protect é um modelo voltado para oferecer máxima segurança e tecnologia avançada. Ideal para famílias que buscam um carro moderno e seguro.',
        motor: "2.0 Flex",
        preco: "R$ 150.000",
        cor: "Cinza",
        ano: "2023",
        cambio: "CVT",
        potencia: "150 cv",
        tags: "segurança, tecnologia, moderno, familiar",
        id:"5"
    },
    {
        titulo: "Prince Skyline 1500 Deluxe",
        marca: "Nissan",
        descricao: 'O Prince Skyline 1500 Deluxe é um clássico da década de 1960, símbolo de luxo e performance no Japão. Com um design elegante, este modelo marcou o início da icônica linha Skyline.',
        motor: "1.5",
        preco: "R$ 300.000",
        cor: "Vermelho",
        ano: "1965",
        cambio: "Manual",
        potencia: "70 cv",
        tags: "clássico, luxo, vintage, performance",
        id:"6"
    },
    {
        titulo: "Skyline 2000GT-R",
        marca: "Nissan",
        descricao: 'O Nissan Skyline 2000GT-R é um ícone dos anos 1970. Conhecido como "Godzilla" por seu desempenho nas pistas, ele é um dos modelos mais reverenciados pelos entusiastas de carros esportivos.',
        motor: "2.0",
        preco: "R$ 1.000.000",
        cor: "Prata",
        ano: "1973",
        cambio: "Manual",
        potencia: "160 cv",
        tags: "esportivo, ícone, Godzilla, anos 70",
        id:"7"
    },
    {
        titulo: "Skyline 2000 Turbo RS",
        marca: "Nissan",
        descricao: 'O Skyline 2000 Turbo RS é um carro esportivo japonês que combina estilo e performance. Seu motor turbo o destaca por ser um dos carros mais rápidos de sua época.',
        motor: "2.0 Turbo",
        preco: "R$ 800.000",
        cor: "Preto",
        ano: "1983",
        cambio: "Manual",
        potencia: "150 cv",
        tags: "esportivo, turbo, performance, estilo",
        id:"8"
    },
    {
        titulo: "Skyline GT-R Nürburgring Time Attack",
        marca: "Nissan",
        descricao: 'O Skyline GT-R Nürburgring Time Attack é uma versão especial desenvolvida para quebrar recordes na famosa pista de Nürburgring. Com ajustes de alta performance, ele oferece uma experiência única de velocidade.',
        motor: "2.6 Twin Turbo",
        preco: "R$ 2.500.000",
        cor: "Branco",
        ano: "2002",
        cambio: "Manual",
        potencia: "280 cv",
        tags: "alta performance, Nürburgring, velocidade, edição especial",
        id:"9"
    },
    {
        titulo: "Skyline GT-R M·spec Nür",
        marca: "Nissan",
        descricao: 'O Skyline GT-R M·spec Nür é uma edição limitada que homenageia a lendária pista de Nürburgring. Seu desempenho é incomparável, e ele é um dos modelos mais cobiçados pelos colecionadores.',
        motor: "2.6 Twin Turbo",
        preco: "R$ 2.000.000",
        cor: "Prata",
        ano: "2002",
        cambio: "Manual",
        potencia: "280 cv",
        tags: "edição limitada, Nürburgring, colecionador, desempenho, Bryan, velozes e furiosos",
        id:"10"
    },
    {
        titulo: "Nissan GT-R Bolt Special",
        marca: "Nissan",
        descricao: 'O Nissan GT-R Bolt Special foi criado em homenagem ao velocista Usain Bolt. Esta versão única do GT-R combina alta performance com elementos de design exclusivos, representando a velocidade e o estilo do atleta.',
        motor: "3.8 V6 Twin Turbo",
        preco: "R$ 3.000.000",
        cor: "Ouro",
        ano: "2013",
        cambio: "Automático",
        potencia: "600 cv",
        tags: "edição especial, alta performance, Usain Bolt, design exclusivo",
        id:"11"
    },
    {
        titulo: "BMW X6 M Competition",
        marca: "BMW",
        descricao: 'O BMW X6 M Competition combina o design robusto de um SUV com a potência de um carro esportivo, oferecendo alto desempenho com tecnologia de ponta.',
        motor: "4.4 V8 TwinPower Turbo",
        preco: "R$ 1.200.000",
        cor: "Preto",
        ano: "2023",
        cambio: "Automático",
        potencia: "625 cv",
        tags: "SUV, esportivo, potência, tecnologia",
        id:"12"
    },
    {
        titulo: "BMW M3 Competition",
        marca: "BMW",
        descricao: 'O BMW M3 Competition é um sedã de alta performance, projetado para quem busca uma combinação de luxo, tecnologia e potência nas pistas.',
        motor: "3.0 I6 TwinPower Turbo",
        preco: "R$ 950.000",
        cor: "Verde",
        ano: "2023",
        cambio: "Automático",
        potencia: "510 cv",
        tags: "sedã, alta performance, luxo, tecnologia",
        id:"13"
    },
    {
        titulo: "BMW 320i",
        marca: "BMW",
        descricao: 'O BMW 320i é um sedã premium que combina conforto, tecnologia e um excelente desempenho em todas as condições de condução.',
        motor: "2.0 TwinPower Turbo",
        preco: "R$ 350.000",
        cor: "Branco",
        ano: "2023",
        cambio: "Automático",
        potencia: "184 cv",
        tags: "sedã, premium, conforto, tecnologia",
        id:"14"
    },
    {
        titulo: "BMW M4 Competition",
        marca: "BMW",
        descricao: 'O BMW M4 Competition é um coupé esportivo que oferece uma condução emocionante com um design aerodinâmico e um motor de alto desempenho.',
        motor: "3.0 I6 TwinPower Turbo",
        preco: "R$ 1.000.000",
        cor: "Amarelo",
        ano: "2023",
        cambio: "Automático",
        potencia: "510 cv",
        tags: "coupé, esportivo, desempenho, aerodinâmico",
        id:"15"
    },
    {
        titulo: "BMW M3 GTR",
        marca: "BMW",
        descricao: 'O BMW M3 GTR é um modelo lendário no mundo das corridas, especialmente conhecido por sua vitória no American Le Mans Series e pelo seu motor V8.',
        motor: "4.0 V8",
        preco: "R$ 2.500.000",
        cor: "Cinza",
        ano: "2001",
        cambio: "Manual",
        potencia: "493 cv",
        tags: "corrida, performance, lendário, design",
        id:"16"
    },
    {
        titulo: "BMW R 1250 GS Adventure",
        marca: "BMW",
        descricao: 'A BMW R 1250 GS Adventure é uma moto projetada para longas viagens, oferecendo resistência e conforto em qualquer tipo de terreno.',
        motor: "1254 cc Boxer",
        preco: "R$ 130.000",
        cor: "Azul",
        ano: "2023",
        cambio: "Manual",
        potencia: "136 cv",
        tags: "aventura, off-road, conforto, resistência",
        id:"17"
    },
    {
        titulo: "BMW F 750 GS",
        marca: "BMW",
        descricao: 'A BMW F 750 GS é uma moto versátil, ideal para aventuras em estradas e trilhas, com excelente controle e desempenho.',
        motor: "853 cc",
        preco: "R$ 90.000",
        cor: "Vermelho",
        ano: "2023",
        cambio: "Manual",
        potencia: "77 cv",
        tags: "versátil, trilha, controle, desempenho",
        id:"18"
    },
    {
        titulo: "BMW S 1000 RR",
        marca: "BMW",
        descricao: 'A BMW S 1000 RR é uma superbike de alto desempenho, conhecida por sua agilidade e potência, perfeita para quem busca velocidade nas pistas.',
        motor: "999 cc",
        preco: "R$ 140.000",
        cor: "Branco/Preto",
        ano: "2023",
        cambio: "Manual",
        potencia: "207 cv",
        tags: "superbike, agilidade, velocidade, desempenho",
        id:"19"
    },
    {
        titulo: "BMW R 18",
        marca: "BMW",
        descricao: 'A BMW R 18 é uma motocicleta cruiser que combina um design clássico com tecnologia moderna e um motor poderoso, proporcionando uma experiência única de pilotagem.',
        motor: "1802 cc Boxer",
        preco: "R$ 160.000",
        cor: "Preto",
        ano: "2023",
        cambio: "Manual",
        potencia: "91 cv",
        tags: "cruiser, design clássico, potência, tecnologia",
        id:"20"
    },
    {
        titulo: "BMW C 400 X",
        marca: "BMW",
        descricao: 'O BMW C 400 X é um scooter compacto e moderno, ideal para quem busca mobilidade urbana com estilo e praticidade.',
        motor: "350 cc",
        preco: "R$ 50.000",
        cor: "Azul",
        ano: "2023",
        cambio: "Automático",
        potencia: "34 cv",
        tags: "scooter, mobilidade, urbano, estilo",
        id:"21"
    },
    {
        titulo: "Mercedes-Benz 300 SLR Uhlenhaut Coupe",
        marca: "Mercedes-Benz",
        descricao: 'O Mercedes-Benz 300 SLR Uhlenhaut Coupe é um dos carros mais icônicos e valiosos do mundo, projetado como uma versão de corrida, mas que acabou se tornando um símbolo de exclusividade.',
        motor: "3.0L Straight-8",
        preco: "R$ 850.000.000",
        cor: "Prata",
        ano: "1955",
        cambio: "Manual",
        potencia: "310 cv",
        tags: "icônico, exclusivo, corrida, valioso",
        id:"22"
    },
    {
        titulo: "Mercedes-AMG Project One",
        marca: "Mercedes-AMG",
        descricao: 'O Mercedes-AMG Project One traz tecnologia de Fórmula 1 para as ruas, com seu motor híbrido e desempenho extraordinário, sendo um dos supercarros mais avançados da atualidade.',
        motor: "1.6L V6 Turbo Híbrido",
        preco: "R$ 25.000.000",
        cor: "Cinza",
        ano: "2023",
        cambio: "Automático",
        potencia: "1.000 cv",
        tags: "Fórmula 1, híbrido, supercarro, tecnologia",
        id:"23"
    },
    {
        titulo: "Mercedes-Benz Maybach Exelero",
        marca: "Mercedes-Maybach",
        descricao: 'O Mercedes-Benz Maybach Exelero é um dos carros mais exclusivos e caros já produzidos, combinando luxo extremo com um desempenho impressionante, destinado a poucos.',
        motor: "6.0L V12 Twin Turbo",
        preco: "R$ 50.000.000",
        cor: "Preto",
        ano: "2005",
        cambio: "Automático",
        potencia: "700 cv",
        tags: "luxo, exclusivo, desempenho, caro",
        id:"24"
    },
    {
        titulo: "Mercedes-Maybach S 680 4MATIC",
        marca: "Mercedes-Maybach",
        descricao: 'O Mercedes-Maybach S 680 4MATIC é a representação máxima de luxo e conforto, com tecnologias inovadoras e um motor potente para quem busca a melhor experiência automotiva.',
        motor: "6.0L V12",
        preco: "R$ 3.500.000",
        cor: "Branco",
        ano: "2023",
        cambio: "Automático",
        potencia: "630 cv",
        tags: "luxo, conforto, tecnologia, potência",
        id:"25"
    },
    {
        titulo: "Mercedes-Benz SLR McLaren Stirling Moss",
        marca: "Mercedes-Benz",
        descricao: 'O Mercedes-Benz SLR McLaren Stirling Moss é uma edição limitada e sem teto, inspirada nos carros de corrida dos anos 50. Com um design único e uma performance arrebatadora, é um verdadeiro colecionável.',
        motor: "5.4L V8 Supercharged",
        preco: "R$ 12.000.000",
        cor: "Prata",
        ano: "2009",
        cambio: "Automático",
        potencia: "650 cv",
        tags: "edição limitada, colecionável, design único, performance",
        id:"26"
    },
    {
        titulo: "Mercedes-AMG GT Black Series",
        marca: "Mercedes-AMG",
        descricao: 'O Mercedes-AMG GT Black Series é a versão mais radical da linha AMG GT, com um motor V8 afinado para proporcionar o máximo desempenho em pistas.',
        motor: "4.0L V8 Biturbo",
        preco: "R$ 3.800.000",
        cor: "Laranja",
        ano: "2023",
        cambio: "Automático",
        potencia: "730 cv",
        tags: "radical, desempenho, pista, V8",
        id:"27"
    },
    {
        titulo: "Mercedes-Benz G 63 AMG 6x6",
        marca: "Mercedes-Benz",
        descricao: 'O Mercedes-Benz G 63 AMG 6x6 é uma verdadeira máquina off-road, combinando o desempenho bruto com o luxo inigualável da marca Mercedes-Benz, com seis rodas motrizes.',
        motor: "5.5L V8 Biturbo",
        preco: "R$ 6.000.000",
        cor: "Preto",
        ano: "2015",
        cambio: "Automático",
        potencia: "544 cv",
        tags: "off-road, luxo, 6x6, potência",
        id:"28"
    },
    {
        titulo: "Mercedes-Maybach GLS 600 4MATIC",
        marca: "Mercedes-Maybach",
        descricao: 'O Mercedes-Maybach GLS 600 4MATIC é o SUV de luxo definitivo, combinando a robustez de um utilitário com o conforto e tecnologia característicos da marca Maybach.',
        motor: "4.0L V8 Biturbo",
        preco: "R$ 2.800.000",
        cor: "Azul",
        ano: "2023",
        cambio: "Automático",
        potencia: "558 cv",
        tags: "SUV, luxo, conforto, tecnologia",
        id:"29"
    },
    {
        titulo: "Mercedes-Benz S 680 Guard 4MATIC",
        marca: "Mercedes-Benz",
        descricao: 'O Mercedes-Benz S 680 Guard 4MATIC é um sedã blindado de luxo, projetado para garantir a máxima segurança sem comprometer o conforto e o desempenho.',
        motor: "6.0L V12",
        preco: "R$ 4.500.000",
        cor: "Preto",
        ano: "2023",
        cambio: "Automático",
        potencia: "630 cv",
        tags: "blindado, luxo, segurança, conforto",
        id:"30"
    },
    {
        titulo: "Mercedes-AMG G63 4x4²",
        marca: "Mercedes-AMG",
        descricao: 'O Mercedes-AMG G63 4x4² é uma versão extrema do clássico G-Wagon, projetado para encarar os terrenos mais difíceis com estilo e potência.',
        motor: "4.0L V8 Biturbo",
        preco: "R$ 2.500.000",
        cor: "Verde",
        ano: "2023",
        cambio: "Automático",
        potencia: "585 cv",
        tags: "extremo, off-road, potência, estilo",
        id:"31"
    },
    {
        titulo: "Mitsubishi Lancer Evolution",
        marca: "Mitsubishi",
        descricao: 'O Mitsubishi Lancer Evolution, também conhecido como Evo, é um dos carros esportivos mais icônicos, projetado com foco em alta performance e tração nas quatro rodas.',
        motor: "2.0L Turbo I4",
        preco: "R$ 200.000",
        cor: "Branco",
        ano: "2015",
        cambio: "Automático",
        potencia: "307 cv",
        tags: "Esportivo, Tração 4x4, Desempenho Alto",
        id:"32"
    },
    {
        titulo: "Mitsubishi Pajero/Montero",
        marca: "Mitsubishi",
        descricao: 'O Mitsubishi Pajero, também conhecido como Montero em alguns mercados, é um SUV robusto com excelentes capacidades off-road, ideal para aventuras em qualquer terreno.',
        motor: "3.8L V6",
        preco: "R$ 350.000",
        cor: "Preto",
        ano: "2023",
        cambio: "Automático",
        potencia: "250 cv",
        tags: "SUV, Off-Road, Aventura",
        id:"33"
    },
    {
        titulo: "Mitsubishi Outlander",
        marca: "Mitsubishi",
        descricao: 'O Mitsubishi Outlander é um SUV versátil que combina conforto, tecnologia e desempenho, sendo uma excelente opção para famílias e para o uso urbano.',
        motor: "2.4L I4",
        preco: "R$ 250.000",
        cor: "Cinza",
        ano: "2023",
        cambio: "Automático",
        potencia: "167 cv",
        tags: "SUV, Família, Tecnologia",
        id:"34"
    },
    {
        titulo: "Mitsubishi Eclipse",
        marca: "Mitsubishi",
        descricao: 'O Mitsubishi Eclipse é um coupé esportivo popular nos anos 90 e 2000, famoso por seu desempenho dinâmico e estilo arrojado, sendo um clássico entre os entusiastas de carros.',
        motor: "2.0L Turbo I4",
        preco: "R$ 150.000",
        cor: "Vermelho",
        ano: "2005",
        cambio: "Manual",
        potencia: "210 cv",
        tags: "Coupé, Clássico, Desempenho",
        id:"35"
    },
    {
        titulo: "Mitsubishi 3000GT (GTO)",
        marca: "Mitsubishi",
        descricao: 'O Mitsubishi 3000GT, também conhecido como GTO em alguns mercados, é um dos carros esportivos mais avançados da década de 90, equipado com tração nas quatro rodas e tecnologias inovadoras.',
        motor: "3.0L V6 Twin Turbo",
        preco: "R$ 400.000",
        cor: "Verde",
        ano: "1999",
        cambio: "Manual",
        potencia: "320 cv",
        tags: "Esportivo, Tecnologia, Tração 4x4",
        id:"36"
    },
    {
        titulo: "Mitsubishi Mirage",
        marca: "Mitsubishi",
        descricao: 'O Mitsubishi Mirage é um hatch compacto, econômico e prático, ideal para uso urbano e muito apreciado por sua eficiência de combustível.',
        motor: "1.2L I3",
        preco: "R$ 90.000",
        cor: "Azul",
        ano: "2023",
        cambio: "Automático",
        potencia: "78 cv",
        tags: "Compacto, Econômico, Uso Urbano",
        id:"37"
    },
    {
        titulo: "Mitsubishi ASX (RVR/Outlander Sport)",
        marca: "Mitsubishi",
        descricao: 'O Mitsubishi ASX, também conhecido como RVR ou Outlander Sport, é um SUV compacto que oferece versatilidade, segurança e eficiência, perfeito para o uso cotidiano.',
        motor: "2.0L I4",
        preco: "R$ 180.000",
        cor: "Prata",
        ano: "2023",
        cambio: "Automático",
        potencia: "150 cv",
        tags: "SUV Compacto, Versátil, Segurança",
        id:"38"
    },
    {
        titulo: "Mitsubishi Galant",
        marca: "Mitsubishi",
        descricao: 'O Mitsubishi Galant é um sedã clássico, com foco em conforto e confiabilidade, sendo uma escolha popular durante décadas em várias partes do mundo.',
        motor: "2.4L I4",
        preco: "R$ 80.000",
        cor: "Bege",
        ano: "2012",
        cambio: "Automático",
        potencia: "162 cv",
        tags: "Sedã, Conforto, Clássico",
        id:"39"
    },
    {
        titulo: "Mitsubishi Silver Pigeon",
        marca: "Mitsubishi",
        descricao: 'A Mitsubishi Silver Pigeon foi uma scooter produzida pela Mitsubishi após a Segunda Guerra Mundial, sendo um símbolo de mobilidade acessível e popular no Japão.',
        motor: "123 cc",
        preco: "R$ 20.000",
        cor: "Branco",
        ano: "1954",
        cambio: "Manual",
        potencia: "4 cv",
        tags: "Scooter, Histórico, Mobilidade",
        id:"40"
    },
    {
        titulo: "Mitsubishi Meguro K",
        marca: "Mitsubishi",
        descricao: 'A Mitsubishi Meguro K foi uma motocicleta produzida pela Mitsubishi Motors em parceria com a Meguro, marcando o início da entrada da marca no mercado de motocicletas.',
        motor: "500 cc",
        preco: "R$ 35.000",
        cor: "Preto",
        ano: "1962",
        cambio: "Manual",
        potencia: "34 cv",
        tags: "Motocicleta, Histórica, Parceria",
        id:"41"
    },
    {
        titulo: "Aston Martin Valkyrie",
        marca: "Aston Martin",
        descricao: 'O Aston Martin Valkyrie é um hipercarro projetado para oferecer desempenho extremo, com tecnologia derivada da Fórmula 1 e um design inovador.',
        motor: "6.5L V12 Híbrido",
        preco: "R$ 15.000.000",
        cor: "Verde",
        ano: "2021",
        cambio: "Automático",
        potencia: "1.160 cv",
        tags: "Hipercarro, Fórmula 1, Desempenho Extremo",
        id:"42"
    },
    {
        titulo: "Aston Martin One-77",
        marca: "Aston Martin",
        descricao: 'O Aston Martin One-77 é um supercarro exclusivo, com um design arrojado e um motor V12 potente, representando o auge do desempenho e do luxo.',
        motor: "7.3L V12",
        preco: "R$ 8.000.000",
        cor: "Prata",
        ano: "2011",
        cambio: "Automático",
        potencia: "760 cv",
        tags: "Supercarro, Luxo, Desempenho",
        id:"43"
    },
    {
        titulo: "Aston Martin Vulcan",
        marca: "Aston Martin",
        descricao: 'O Aston Martin Vulcan é um carro de pista de edição limitada, projetado para oferecer uma experiência de condução pura e inigualável com um motor V12.',
        motor: "7.0L V12",
        preco: "R$ 10.000.000",
        cor: "Azul",
        ano: "2015",
        cambio: "Sequencial",
        potencia: "800 cv",
        tags: "Carro de Pista, Edição Limitada, Desempenho",
        id:"44"
    },
    {
        titulo: "Aston Martin DBS Superleggera",
        marca: "Aston Martin",
        descricao: 'O Aston Martin DBS Superleggera é um grand tourer de luxo com um motor V12, oferecendo uma combinação de desempenho impressionante e conforto absoluto.',
        motor: "5.2L V12 Twin Turbo",
        preco: "R$ 1.200.000",
        cor: "Preto",
        ano: "2023",
        cambio: "Automático",
        potencia: "725 cv",
        tags: "Grand Tourer, Luxo, Desempenho",
        id:"45"
    },
    {
        titulo: "Aston Martin V12 Zagato",
        marca: "Aston Martin",
        descricao: 'O Aston Martin V12 Zagato é um carro esportivo de edição limitada, criado em parceria com a Zagato, destacando-se por seu design exclusivo e motor V12.',
        motor: "6.0L V12",
        preco: "R$ 2.000.000",
        cor: "Vermelho",
        ano: "2012",
        cambio: "Manual",
        potencia: "510 cv",
        tags: "Edição Limitada, Design Exclusivo, Parceria",
        id:"46"
    },
    {
        titulo: "Aston Martin Vanquish Zagato",
        marca: "Aston Martin",
        descricao: 'O Aston Martin Vanquish Zagato é uma obra-prima de design e desempenho, com uma colaboração exclusiva com a Zagato e um motor V12 poderoso.',
        motor: "5.9L V12",
        preco: "R$ 2.500.000",
        cor: "Branco",
        ano: "2017",
        cambio: "Automático",
        potencia: "591 cv",
        tags: "Design Exclusivo, Zagato, Desempenho",
        id:"47"
    },
    {
        titulo: "Aston Martin Rapide AMR",
        marca: "Aston Martin",
        descricao: 'O Aston Martin Rapide AMR é um sedã de alto desempenho que combina luxo e esportividade, com um motor V12 e características de performance aprimoradas.',
        motor: "6.0L V12",
        preco: "R$ 1.800.000",
        cor: "Azul",
        ano: "2020",
        cambio: "Automático",
        potencia: "603 cv",
        tags: "Sedã, Luxo, Desempenho Alto",
        id:"48"
    },
    {
        titulo: "Aston Martin DB11",
        marca: "Aston Martin",
        descricao: 'O Aston Martin DB11 é um grand tourer elegante e potente, com um design sofisticado e um motor V8 ou V12, proporcionando uma experiência de condução luxuosa.',
        motor: "4.0L V8 Twin Turbo",
        preco: "1.500.000",
        cor: "Prata",
        ano: "2023",
        cambio: "Automático",
        potencia: "503 cv",
        tags: "Grand Tourer, Luxo, Potência",
        id:"49"
    },
    {
        titulo: "Aston Martin V8 Vantage Roadster",
        marca: "Aston Martin",
        descricao: 'O Aston Martin V8 Vantage Roadster é um conversível esportivo que oferece desempenho emocionante e um design elegante, com um motor V8 de alta potência.',
        motor: "4.0L V8 Twin Turbo",
        preco: "R$ 850.000",
        cor: "Cinza",
        ano: "2023",
        cambio: "Automático",
        potencia: "503 cv",
        tags: "Conversível, Esportivo, Desempenho",
        id:"50"
    },
    {
        titulo: "Aston Martin AMB 001",
        marca: "Aston Martin",
        descricao: 'O Aston Martin AMB 001 é uma motocicleta de edição limitada desenvolvida em colaboração com a Brough Superior, combinando design futurista com desempenho de alto nível.',
        motor: "997 cc V-twin Turbo",
        preco: "R$ 2.200.000",
        cor: "Preto",
        ano: "2021",
        cambio: "Manual",
        potencia: "180 cv",
        tags: "Motocicleta, Edição Limitada, Design Futurista",
        id:"51"
    },
    {
        titulo: "Koenigsegg Agera RS",
        marca: "Koenigsegg",
        descricao: 'O Koenigsegg Agera RS é um hipercarro sueco que oferece desempenho extremo, sendo um dos carros mais rápidos e avançados tecnologicamente no mundo.',
        motor: "5.0L V8 Twin Turbo",
        preco: "R$ 15.000.000",
        cor: "Preto",
        ano: "2015",
        cambio: "Sequencial",
        potencia: "1.160 cv",
        tags: "hipercarro, desempenho extremo, tecnologia",
        id:"52"
    },
    {
        titulo: "Koenigsegg Jesko",
        marca: "Koenigsegg",
        descricao: 'O Koenigsegg Jesko é um carro de performance ultrarrápido, com um design inovador e um motor V8 que oferece uma experiência de condução incomparável.',
        motor: "5.0L V8 Twin Turbo",
        preco: "R$ 18.000.000",
        cor: "Branco",
        ano: "2021",
        cambio: "Sequencial",
        potencia: "1.280 cv",
        tags: "performance, inovação, V8",
        id:"53"
    },
    {
        titulo: "Koenigsegg Regera",
        marca: "Koenigsegg",
        descricao: 'O Koenigsegg Regera combina um motor V8 com um sistema híbrido para uma experiência de condução elétrica e de combustão interna, oferecendo potência e eficiência.',
        motor: "5.0L V8 Twin Turbo + Sistema Híbrido",
        preco: "R$ 14.000.000",
        cor: "Dourado",
        ano: "2017",
        cambio: "Automático",
        potencia: "1.500 cv",
        tags: "híbrido, potência, eficiência",
        id:"54"
    },
    {
        titulo: "Koenigsegg CCX",
        marca: "Koenigsegg",
        descricao: 'O Koenigsegg CCX é um carro esportivo de alta performance, conhecido por seu design aerodinâmico e motor potente que oferece uma condução emocionante.',
        motor: "4.7L V8",
        preco: "R$ 8.000.000",
        cor: "Azul",
        ano: "2006",
        cambio: "Sequencial",
        potencia: "806 cv",
        tags: "esportivo, design aerodinâmico, potência",
        id:"55"
    },
    {
        titulo: "Koenigsegg CCXR Trevita",
        marca: "Koenigsegg",
        descricao: 'O Koenigsegg CCXR Trevita é uma edição limitada com uma pintura especial em fibra de carbono e um motor V8 que proporciona desempenho excepcional.',
        motor: "4.8L V8 Twin Turbo",
        preco: "R$ 25.000.000",
        cor: "Branco",
        ano: "2009",
        cambio: "Sequencial",
        potencia: "1.018 cv",
        tags: "edição limitada, fibra de carbono, desempenho",
        id:"56"
    },
    {
        titulo: "Koenigsegg Gemera",
        marca: "Koenigsegg",
        descricao: 'O Koenigsegg Gemera é um carro esportivo de quatro lugares, com um motor híbrido que oferece um equilíbrio perfeito entre desempenho e conforto.',
        motor: "2.0L V8 Twin Turbo + Híbrido",
        preco: "R$ 12.000.000",
        cor: "Cinza",
        ano: "2021",
        cambio: "Automático",
        potencia: "1.700 cv",
        tags: "quatro lugares, híbrido, desempenho",
        id:"57"
    },
    {
        titulo: "Koenigsegg Agera One:1",
        marca: "Koenigsegg",
        descricao: 'O Koenigsegg Agera One:1 é um hipercarro que combina uma relação de potência e peso de 1:1, tornando-o um dos carros mais leves e potentes do mundo.',
        motor: "5.0L V8 Twin Turbo",
        preco: "R$ 20.000.000",
        cor: "Verde",
        ano: "2014",
        cambio: "Sequencial",
        potencia: "1.341 cv",
        tags: "hipercarro, potência, leveza",
        id:"58"
    },
    {
        titulo: "Koenigsegg CC850",
        marca: "Koenigsegg",
        descricao: 'O Koenigsegg CC850 é um carro esportivo que oferece uma combinação de tecnologia moderna com um motor V8 poderoso, projetado para proporcionar uma experiência de condução excepcional.',
        motor: "5.0L V8 Twin Turbo",
        preco: "R$ 13.000.000",
        cor: "Prata",
        ano: "2023",
        cambio: "Sequencial",
        potencia: "1.185 cv",
        tags: "tecnologia, motor V8, experiência de condução",
        id:"59"
    },
    {
        titulo: "Koenigsegg Agera R",
        marca: "Koenigsegg",
        descricao: 'O Koenigsegg Agera R é um carro esportivo de alto desempenho com um motor V8 turboalimentado que oferece velocidade e agilidade impressionantes.',
        motor: "5.0L V8 Twin Turbo",
        preco: "9.000.000",
        cor: "Preto",
        ano: "2011",
        cambio: "Sequencial",
        potencia: "1.115 cv",
        tags: "alto desempenho, turboalimentado, velocidade",
        id:"60"
    },
    {
        titulo: "Koenigsegg CC8S",
        marca: "Koenigsegg",
        descricao: 'O Koenigsegg CC8S é um dos primeiros modelos da marca, conhecido por seu design único e motor V8 que oferece um desempenho impressionante.',
        motor: "4.7L V8",
        preco: "R$ 7.000.000",
        cor: "Vermelho",
        ano: "2002",
        cambio: "Sequencial",
        potencia: "655 cv",
        tags: "design único, desempenho, V8",
        id:"61"
    }
];
